# Generated by Django 3.2 on 2021-05-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent',
            name='name_endonym',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='name_exonym',
        ),
        migrations.AddField(
            model_name='continent',
            name='abbreviation',
            field=models.CharField(default='NA', max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='continent',
            name='name',
            field=models.CharField(default='NA', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
