# Generated by Django 3.2 on 2021-05-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0002_auto_20210504_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital_endonym',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital_exonym',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
