# Generated by Django 3.2 on 2021-05-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0003_auto_20210504_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_exonym', models.CharField(max_length=255, unique=True)),
                ('name_endonym', models.CharField(max_length=255)),
                ('iso_639_1', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(to='django_useful_models.Language'),
        ),
    ]
