# Generated by Django 3.2 on 2021-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0004_auto_20210504_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso_639_1',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_endonym',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_exonym',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
