# Generated by Django 3.2 on 2021-05-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0005_auto_20210504_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='calling_code',
            field=models.IntegerField(max_length=4),
        ),
    ]
