# Generated by Django 3.2 on 2021-05-04 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0006_alter_country_calling_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='iso_3166_1_alpha_2',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Exactly two uppercase letters required.', regex='^[A-Z]{2}$')]),
        ),
        migrations.AlterField(
            model_name='country',
            name='calling_code',
            field=models.CharField(max_length=20),
        ),
    ]
