# Generated by Django 3.2 on 2021-05-04 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0008_alter_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_useful_models.currency'),
        ),
    ]
