# Generated by Django 3.2 on 2021-05-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0009_country_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
    ]
