# Generated by Django 3.2 on 2021-05-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0012_rename_currency_country_currencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
        migrations.AddField(
            model_name='currency',
            name='name_plural',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol_endonym',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol_exonym',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
