# Generated by Django 3.2 on 2021-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0013_auto_20210504_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('utc_offset', models.DurationField()),
                ('utc_dst_offset', models.DurationField(help_text='Daylight saving offset')),
            ],
        ),
    ]
