# Generated by Django 3.2 on 2021-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_useful_models', '0014_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='utc_dst_offset',
            field=models.DurationField(help_text='Daylight saving offset', null=True),
        ),
    ]
